repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: catatonia
        name: perform code formatting & otimizations
        language: system
        pass_filenames: false
        entry: bash
        args:
          - -ceu
          - --
          - |
            docker run --rm --pull=missing -v "$PWD:/data" ghcr.io/willtobyte/catatonia:latest
