---@type fun():string
moment = moment

---@type fun(url:string)
openurl = openurl

---@type fun(state:userdata, module:string):fun
searcher = searcher

---@type JSON
JSON = JSON

---@type any
_ = _

---@enum WidgetType
WidgetType = {
	cursor = 0,
	label = 1,
}

---@enum SceneType
SceneType = {
	object = 0,
	effect = 1,
}

---@class EngineFactory
---@field new fun():EngineFactory Constructor for EngineFactory
EngineFactory = EngineFactory

---@class PostalService
---@field new fun():PostalService Constructor for PostalService
PostalService = PostalService

---@type Engine engine
---@class Overlay
---@field create fun(self:Overlay, widgetType:WidgetType):Label Create a widget instance of the specified type and return it.
---@field destroy fun(self:Overlay, widgetId:number) Destroy a widget by ID.
---@field dispatch fun(self:Overlay, widgetType:WidgetType, eventName:string):boolean Dispatch an event of `eventName` for the specified widget type.
---@field cursor CursorProxy Proxy to manage the overlay cursor.
---@type Overlay overlay
---@class SceneManager
---@field set fun(self:SceneManager, name:string) Switch to the named scene.
---@field register fun(self:SceneManager, name:string) Load and register a scene from scripts/<name>.lua.
---@field destroy fun(self:SceneManager, name:string) Destroy the named scene.
---@type SceneManager scenemanager

---@class TimerManager
---@field set fun(self:TimerManager, interval:number, callback:fun()):number Schedule a repeating callback; returns timer ID.
---@field singleshot fun(self:TimerManager, delay:number, callback:fun()):number Schedule a one-time callback; returns timer ID.
---@field clear fun(self:TimerManager, id:number) Clear the specified scheduled callback by its timer ID.
---@type TimerManager timermanager

---@meta
--- Type definitions for the Ultratech Lua Script Engine Binding
--- Autogenerated from C++ `scriptengine` bindings for improved editor IntelliSense and documentation.

---@class ActionProxy
---Proxy to manage an object's action property.
---@field set fun(self:ActionProxy, value:string) Sets the action on the object.
---@field get fun(self:ActionProxy):string Retrieves the current action of the object.
---@field unset fun(self:ActionProxy) Unsets the object's action.

---@enum Anchor
---Anchor enumeration for object alignment (framework.anchor).
Anchor = {
	---Align to the top.
	top = 0,
	---Align to the bottom.
	bottom = 1,
	---Align to the left.
	left = 2,
	---Align to the right.
	right = 3,
	---No anchoring.
	none = 4,
}

---@class Canvas
---Canvas for direct pixel manipulation.
---Use the `pixels` property to update pixel data.
---@field pixels fun(self:Canvas, data:table) Sets the pixel data from a sequential table of RGBA values.

---@class Cassette
---Persistent key-value storage interface.
---@field clear fun(self:Cassette) Clears all stored key-value pairs.
---@field set fun(self:Cassette, key:string, value:any) Stores a value under the given key.
---@field get fun(self:Cassette, key:string, default:any):any Retrieves a value or returns the provided default.

---@class Color
---RGBA color representation.
---@overload fun(color:string):Color Constructs a Color from a hex string (e.g., "#RRGGBB").
---@field r number Red channel (0–255).
---@field g number Green channel (0–255).
---@field b number Blue channel (0–255).
---@field a number Alpha channel (0–255).

---@class Controller
---Gamepad controller button codes (input.event.gamepad.button).
---@field up number The "up" button code.
---@field down number The "down" button code.
---@field left number The "left" button code.
---@field right number The "right" button code.
---@field triangle number The "triangle" button code.
---@field circle number The "circle" button code.
---@field cross number The "cross" button code.
---@field square number The "square" button code.

---@class CursorProxy
---Proxy for overlay cursor control.
---@field set fun(self:CursorProxy, name:string) Sets the current cursor by name.
---@field hide fun(self:CursorProxy) Hides the cursor.

---@class Engine
---Core engine instance for running scenes and loops.
---@field canvas fun(self:Engine):Canvas Access the main drawing canvas.
---@field cassette fun(self:Engine):Cassette Access the persistent storage cassette.
---@field objectmanager fun(self:Engine):ObjectManager Manage scene objects.
---@field fontfactory fun(self:Engine):FontFactory Retrieve Font objects.
---@field overlay fun(self:Engine):Overlay Manage UI overlays.
---@field resourcemanager fun(self:Engine):ResourceManager Prefetch and flush resources.
---@field soundmanager fun(self:Engine):SoundManager Play and stop sounds.
---@field statemanager fun(self:Engine):StateManager Query input and collisions.
---@field scenemanager fun(self:Engine):SceneManager Load and register scenes.
---@field timermanager fun(self:Engine):TimerManager Schedule timed callbacks.
---@field run fun(self:Engine) Starts the engine's run loop.

---@class EngineFactory
---Builder for creating Engine instances with custom settings.
---@overload fun():EngineFactory Creates a new EngineFactory.
---@field with_fullscreen fun(self:EngineFactory, fullscreen:boolean):EngineFactory Enable or disable fullscreen mode.
---@field with_gravity fun(self:EngineFactory, x:number, y:number):EngineFactory Set world gravity vector.
---@field with_height fun(self:EngineFactory, height:number):EngineFactory Set window height in pixels.
---@field with_scale fun(self:EngineFactory, scale:number):EngineFactory Set rendering scale factor.
---@field with_title fun(self:EngineFactory, title:string):EngineFactory Set window title.
---@field with_width fun(self:EngineFactory, width:number):EngineFactory Set window width in pixels.
---@field create fun(self:EngineFactory):Engine Creates and returns a configured Engine.

---@class Font
---Font object for rendering text labels.
---@field effect FontEffect Assign a rendering effect to the font (setter proxy).
---Font object for rendering text labels.
---@field effect fun(self:Font, effect:FontEffect) Applies a font rendering effect.

---@enum FontEffect
---Text rendering effects (graphics.fonteffect.type).
FontEffect = {
	---Fade-in effect for text.
	fadein = 0,
}

---@class FontFactory
---Factory to retrieve Font instances.
---@field get fun(self:FontFactory, name:string):Font Retrieves a font by its identifier.

---@class JSON
---JSON encoding and decoding utilities.
---@field parse fun(json:string):table Parses a JSON string into a Lua table.
---@field stringify fun(tbl:table):string Serializes a Lua table into a JSON string.

---@enum KeyEvent
---Keyboard key event codes (input.event.keyboard.key).
KeyEvent = {
	up = 0,
	left = 1,
	down = 2,
	right = 3,
	space = 4,
}

---@class KeyValue
---Key-value interface attached to objects.
---@field get fun(self:KeyValue, key:string, default:any):any Retrieves stored value or default.
---@field set fun(self:KeyValue, key:string, value:any) Stores a new value.
---@field subscribe fun(self:KeyValue, key:string, callback:fun(newValue:any)) Subscribe to key changes.

---@class Label
---Text label widget (inherits from Widget).
---@field font Font Property to set the label's font.
---@field set fun(self:Label, text:string, x:number, y:number) Set the displayed text at position (x, y).
---@field clear fun(self:Label) Clear the text.

---@class Mail
---Mail object for inter-object messaging.
---@overload fun(src:Object, dest:Object|nil, message:string):Mail Constructs a new Mail instance.

---@class MemoryKV
---Alias type for Key-Value storage on objects.
---@field get fun(self:MemoryKV, key:string, default:any):any
---@field set fun(self:MemoryKV, key:string, value:any)
---@field subscribe fun(self:MemoryKV, key:string, callback:fun(newValue:any))

---@class Object
---Core scene object with position, scaling, and event callbacks.
---@field id number Unique object identifier.
---@field x number X position in pixels.
---@field y number Y position in pixels.
---@field alpha number Transparency (0.0–1.0).
---@field scale number Uniform scale factor.
---@field hide fun(self:Object) Hide the object from view.
---@field move fun(self:Object, x:number, y:number) Instantly move the object.
---@field on_update fun(self:Object, callback:fun(dt:number)) Register update callback.
---@field on_animationfinished fun(self:Object, callback:fun()) Register callback on animation end.
---@field on_collision fun(self:Object, callback:fun(other:Object)) Register collision callback.
---@field on_hover fun(self:Object, callback:fun()) Register hover callback.
---@field on_unhover fun(self:Object, callback:fun()) Register unhover callback.
---@field on_touch fun(self:Object, callback:fun(x:number, y:number)) Register touch callback.
---@field on_motion fun(self:Object, callback:fun(dx:number, dy:number)) Register motion callback.
