on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CARIMBO_TAG: "v1.1.3"

    permissions:
      contents: write

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install --yes p7zip-full

      - name: Create bundle
        run: 7z a -xr'!icon.png' -xr'!.git/*' -xr'!.git' -xr'!.*' -t7z -m0=lzma -mx=6 -mfb=64 -md=32m -ms=on bundle.7z .

      - name: Download Carimbo WebAssembly runtime
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release download ${{ env.CARIMBO_TAG }} --repo willtobyte/carimbo --pattern "WebAssembly.zip"

      - name: Extract Carimbo runtime
        run: 7z x WebAssembly.zip -o.

      - name: Copy files
        run: |
          mkdir -p output
          mv bundle.7z output/
          mv carimbo.js output/
          mv carimbo.wasm output/

      - name: Create HTML index file
        run: |
          cat << 'EOF' > output/index.html
          <!doctype html>
          <html lang="en">
            <head>
              <meta charset="UTF-8" />
              <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
              <style>
                *,
                *::before,
                *::after {
                  box-sizing: border-box;
                }

                * {
                  margin: 0;
                }

                body {
                  margin: 0;
                  display: flex;
                  justify-content: center;
                  align-items: center;
                  height: 100vh;
                }

                .container {
                  width: 100%;
                  height: 100%;
                  display: flex;
                  align-items: center;
                  justify-content: center;
                }

                canvas {
                  display: block;
                  width: 100%;
                  max-width: 100vw;
                  max-height: 100vh;
                  aspect-ratio: 16 / 9;
                }
              </style>
            </head>

            <body>
              <div class="container">
                <canvas id="canvas" oncontextmenu="event.preventDefault()"></canvas>
              </div>

              <script type="module">
                const canvas = document.getElementById("canvas");

                const response = await fetch("bundle.7z");
                const bundle = await response.arrayBuffer();

                window.Module = {
                  canvas,
                  noInitialRun: true,
                  onRuntimeInitialized: () => {
                    FS.writeFile("/bundle.7z", new Uint8Array(bundle));
                    Module.callMain();
                  },
                };

                const script = document.createElement("script");
                script.src = "carimbo.js";
                script.defer = true;
                document.body.appendChild(script);
              </script>
            </body>
          </html>
          EOF

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HETZNER_IP }} >> ~/.ssh/known_hosts

      - name: Create Dockerfile
        run: |
          cat > Dockerfile <<'EOF'
            FROM python:3.13-slim
            WORKDIR /app
            COPY output/ .
            EXPOSE 8000
            CMD ["python", "-m", "http.server", "8000"]
          EOF

      - name: Build Docker image with tag "web"
        env:
          DOCKER_HOST: ssh://root@${{ secrets.HETZNER_IP }}
        run: |
          docker build -t web .

      - name: Create docker-compose.yaml file
        run: |
          cat << 'EOF' > docker-compose.yaml
          services:
            web:
              build: .
              image: web
              restart: unless-stopped

            cloudflare:
              image: cloudflare/cloudflared:latest
              environment:
                - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
              command: tunnel --no-autoupdate run
              restart: unless-stopped
          EOF

      - name: Deploy Docker Compose
        env:
          DOCKER_HOST: ssh://root@${{ secrets.HETZNER_IP }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        run: |
          set -e

          docker compose down --remove-orphans
          docker system prune --all --force
          docker compose up --build --force-recreate --detach

          docker ps -a
