name: Publish Google Play

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    if: true

    env:
      CARIMBO_TAG: "v1.3.52"
      ANDROID_API_LEVEL: "34"
      BUILD_TOOLS_VERSION: "34.0.0"

    permissions:
      contents: write

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses

          sdkmanager "platform-tools" "platforms;android-${ANDROID_API_LEVEL}" "build-tools;${BUILD_TOOLS_VERSION}"

          PLATFORM_DIR="$ANDROID_SDK_ROOT/platforms/android-${ANDROID_API_LEVEL}"

          echo "PLATFORM_DIR=$PLATFORM_DIR" >> "$GITHUB_ENV"
          echo "BUILD_TOOLS_VERSION=$BUILD_TOOLS_VERSION" >> "$GITHUB_ENV"
          echo "$ANDROID_SDK_ROOT/build-tools/$BUILD_TOOLS_VERSION" >> "$GITHUB_PATH"

      - name: Debug android.jar presence
        run: |
          ls -l $ANDROID_SDK_ROOT/platforms/android-34/android.jar

      - name: Enforce fullscreen
        run: |
          sed -i -E 's/^(\s*:with_fullscreen\s*)\(false\)/\1(true)/' scripts/main.lua

      - name: Create bundle
        run: |
          7z a bundle.7z \
            . \
            -xr!icon.png \
            -xr!.git \
            -xr!.* \
            -t7z \
            -m0=lzma2 \
            -mx=2 \
            -mfb=8 \
            -md=32k \
            -ms=off \
            -mmt=off

      - name: Download Carimbo runtime
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ env.CARIMBO_TAG }} --repo willtobyte/carimbo --pattern "Android.tar.gz"

      - name: Extract Carimbo runtime
        run: |
          tar -xzf Android.tar.gz
          mkdir -p lib/arm64-v8a
          mv libcarimbo.so lib/arm64-v8a/libmain.so

      - name: Create AndroidManifest.xml
        run: |
          mkdir -p build
          cat <<EOF > build/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="run.carimbo.reprobate"
              android:versionCode="1"
              android:versionName="1.0">
              <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="34" />
              <application android:label="Carimbo" android:hasCode="false"
                          android:allowBackup="true"
                          android:theme="@android:style/Theme.NoTitleBar.Fullscreen">
                  <activity android:name="android.app.NativeActivity"
                            android:label="Carimbo"
                            android:configChanges="orientation|keyboardHidden"
                            android:launchMode="singleTask"
                            android:screenOrientation="landscape"
                            android:exported="true">
                      <meta-data android:name="android.app.lib_name"
                                android:value="main" />
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF

      # - name: Create minimal resource
      #   run: |
      #     mkdir -p res/values
      #     echo '<resources><string name="app_name">Carimbo</string></resources>' > res/values/strings.xml

      - name: Build APK
        run: |
          set -e
          cp bundle.7z lib/arm64-v8a/

          aapt package -f \
                      -M build/AndroidManifest.xml \
                      -S res -A assets \
                      -I "$PLATFORM_DIR/android.jar" \
                      -F app.unaligned.apk \
                      -0 arsc

          zip -r app.unaligned.apk lib

          zipalign -p -f 4 app.unaligned.apk app.aligned.apk

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release-key.jks

      - name: Sign APK
        run: |
          apksigner sign \
            --ks release-key.jks \
            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --out app.apk app.aligned.apk

      - name: Verify APK Signature
        run: |
          apksigner verify --verbose app.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.apk
