name: Publish Steam

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    if: true

    env:
      CARIMBO_TAG: "v6.0.7"

    permissions:
      contents: write

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Enforce fullscreen
        run: |
          sed -i -E 's/^(\s*:with_fullscreen\s*)\(false\)/\1(true)/' scripts/main.lua

      - name: Create cartridge
        run: |
          find . -name '.*' ! -name '.' ! -name '..' -print
          find . -name '.*' ! -name '.' ! -name '..' -exec rm -rf {} +

          zip -r cartridge.rom .

      - name: Download Carimbo runtime
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ env.CARIMBO_TAG }} --repo willtobyte/carimbo --pattern "macOS.tar.gz"
          gh release download ${{ env.CARIMBO_TAG }} --repo willtobyte/carimbo --pattern "Windows.zip"

      - name: Extract Carimbo runtime
        run: |
          unzip Windows.zip -d .
          tar -xzf macOS.tar.gz

      - name: Install Sentry CLI
        run: |
          curl -sL https://sentry.io/get-cli/ | bash

      - name: Upload debug symbols to Sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        run: |
          sentry-cli debug-files upload \
            --include-sources \
            --log-level=info \
            carimbo.pdb

      - name: Clone Steam SDK
        run: gh repo clone willtobyte/steamworks steamworks
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create BUGS file
        run: |
          echo "Please report any comments to rodrigo@delduca.org." > BUGS

      - name: Create VERSION file
        run: |
          echo "Carimbo: $CARIMBO_TAG" > VERSION
          echo "Game: ${{ github.ref_name }}" >> VERSION
          echo "Site: https://carimbo.site" >> VERSION

      - name: Copy files
        run: |
          mkdir -p output/{macos,windows}

          cp cartridge.rom output/macos/
          cp cartridge.rom output/windows/

          cp carimbo output/macos/
          cp crashpad_handler output/macos/
          cp steamworks/redistributable_bin/osx/libsteam_api.dylib output/macos/

          cp carimbo.exe output/windows/
          cp crashpad_handler.exe output/windows/
          cp steamworks/redistributable_bin/win64/steam_api64.dll output/windows/

          for d in output/{macos,windows}; do
            cp BUGS LICENSES VERSION "$d/"
          done

      - name: Upload build to Steam
        uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
          buildDescription: ${{ github.ref_name }}
          appId: ${{ secrets.STEAM_APP_ID }}
          rootPath: output
          depot1Path: windows
          depot2Path: macos
          releaseBranch: alpha
