name: Publish Online

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    if: true

    env:
      CARIMBO_TAG: "v1.3.131"

    permissions:
      contents: write

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Enforce non-fullscreen
        run: |
          sed -i -E 's/^(\s*:with_fullscreen\s*)\(true\)/\1(false)/' scripts/main.lua

      - name: Create bundle
        run: |
          7z a bundle.7z \
            . \
            -xr!icon.png \
            -xr!.git/* \
            -xr!.git \
            -xr!.* \
            -t7z \
            -m0=lzma2 \
            -mx=2 \
            -mfb=8 \
            -md=32k \
            -ms=off \
            -mmt=on

      - name: Download Carimbo WebAssembly runtime
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release download ${{ env.CARIMBO_TAG }} --repo willtobyte/carimbo --pattern "WebAssembly.zip"

      - name: Extract Carimbo runtime
        run: 7z x WebAssembly.zip -o.

      - name: Copy files
        run: |
          mkdir -p output
          touch output/favicon.ico
          mv bundle.7z output/
          mv carimbo.js output/
          mv carimbo.wasm output/

      - name: Create _headers file
        run: |
          cat << EOF > output/_headers
          /
            Cache-Control: no-cache, no-store, must-revalidate

          /*
            Cache-Control: public, max-age=86400, immutable
          EOF

      - name: Set short commit hash
        run: echo "GIT_SHORT_HASH=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Create HTML index file
        run: |
          cat << EOF > output/index.html
          <!doctype html>
          <html lang="en">
            <head>
              <meta charset="UTF-8" />
              <link
                rel="preload"
                href="carimbo.js?v=${GIT_SHORT_HASH}"
                as="script"
              />
              <link
                rel="preload"
                href="carimbo.wasm?v=${GIT_SHORT_HASH}"
                as="fetch"
                type="application/wasm"
                crossorigin
              />
              <link
                rel="preload"
                href="bundle.7z?v=${GIT_SHORT_HASH}"
                as="fetch"
                type="application/octet-stream"
                crossorigin
              />
              <style>
                *,
                *::before,
                *::after {
                  box-sizing: border-box;
                }

                * {
                  margin: 0;
                }

                html, body {
                  width: 100%;
                  height: 100%;
                  margin: 0;
                  display: flex;
                  justify-content: center;
                  align-items: center;
                }

                .container {
                  width: 100%;
                  height: 100%;
                  display: flex;
                  justify-content: center;
                  align-items: center;
                }

                canvas {
                  aspect-ratio: 16 / 9;
                  max-width: 100%;
                  max-height: 100%;
                  width: auto;
                  height: auto;
                  display: block;
                }

                #loading {
                  position: absolute;
                  top: 50%;
                  left: 50%;
                  transform: translate(-50%, -50%);
                  font: 1.25rem sans-serif;
                  color: #666;
                  user-select: none;
                }
              </style>
            </head>

            <body>
              <div class="container">
                <div id="loading">Shining pixels and brushing up bytes...</div>
                <canvas id="canvas" oncontextmenu="event.preventDefault()"></canvas>
              </div>

              <script type="module">
                console.log("${GIT_SHORT_HASH}");

                const canvas = document.getElementById("canvas");
                const loading = document.getElementById("loading");
                const response = await fetch("bundle.7z?v=${GIT_SHORT_HASH}");
                const bundle = await response.arrayBuffer();

                window.Module = {
                  canvas,
                  noInitialRun: true,
                  locateFile: (path) => {
                    if (path.endsWith('.wasm')) {
                      return path + '?v=${GIT_SHORT_HASH}';
                    }
                  },
                  onRuntimeInitialized: () => {
                    loading.remove();
                    FS.writeFile("/bundle.7z", new Uint8Array(bundle));
                    Module.callMain();
                  },
                };

                const script = document.createElement("script");
                script.src = "carimbo.js?v=${GIT_SHORT_HASH}";
                script.defer = true;
                document.body.appendChild(script);
              </script>
            </body>
          </html>
          EOF

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./output --branch=main --project-name=${{ secrets.CLOUDFLARE_PAGES_PROJECT }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge Cloudflare Cache
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
                -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
                -H "Content-Type: application/json" \
                --data '{"purge_everything":true}'
